---
# tasks file for cryptopolicy

- name: "Block: set crypto-policy on relevant distributions"
  block:
  - name: "Check existing policy level"
    ansible.builtin.shell: "update-crypto-policies --show"
    register: r_cryptopolicy_check
    changed_when: false
    become: true

  - name: "Set new policy if required using update-crypto-policies"
    ansible.builtin.shell: "update-crypto-policies --set {{ cryptopolicy_level }}"
    when: r_cryptopolicy_check.stdout != cryptopolicy_level
    become: true
    notify: "cryptopolicy reboot system"
# May also be used on Ubuntu?
  when: >
        ( ansible_os_family == RedHat and ansible_distribution_version is version('8', '>=') ) and
        not ( ansible_distribution == Fedora and ansible_distribution_version is version('28', '<') )
