galaxy_info:
  author: Jason Glass
  description: Set up Nagios 4 server
  company: N/A

  license: BSD

  min_ansible_version: 2.11

  platforms:
    - name: CentOS
      versions:
        - 7

  galaxy_tags: []

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
